import {
  Code,
  Server,
  Database,
  Cloud,
  Cpu,
  PenTool,
  Puzzle,
  Monitor,
  Briefcase,
} from "lucide-react";

export const skills = [
  {
    category: "Frontend",
    icon: <Code />,
    items: [
      "React",
      "Next.js",
      "JavaScript",
      "TypeScript",
      "HTML5",
      "CSS3",
      "Tailwind CSS",
      "Shadcn UI",
      "Design Responsivo",
      "Design UI/UX",
    ],
  },
  {
    category: "Backend",
    icon: <Server />,
    items: [
      "Bun",
      "Node.js",
      "NestJS",
      "Express.js",
      "Python",
      "Django",
      "APIs RESTful",
      "GraphQL",
      "Microserviços",
      "Arquitetura Serverless",
      "AWS Lambda",
    ],
  },
  {
    category: "Banco de Dados",
    icon: <Database />,
    items: [
      "SQL",
      "PostgreSQL",
      "MySQL",
      "MongoDB",
      "Firebase",
      "Supabase",
      "Design de Banco de Dados",
      "Modelagem de Dados",
    ],
  },
  {
    category: "DevOps",
    icon: <Cloud />,
    items: [
      "Docker",
      "GitHub Actions",
      "Vercel",
      "AWS",
      "Azure",
      "Google Cloud Platform (GCP)",
    ],
  },
  {
    category: "IA/ML",
    icon: <Cpu />,
    items: [
      "Transformers",
      "GPT",
      "Claude",
      "Ollama",
      "Fine-Tuning",
      "NLP (Processamento de Linguagem Natural)",
      "TensorFlow",
      "PyTorch",
    ],
  },
  {
    category: "Ferramentas e Métodos",
    icon: <PenTool />,
    items: [
      "Git",
      "GitHub",
      "GitLab",
      "Scrum",
      "Kanban",
      "Desenvolvimento Orientado a Domínio (DDD)",
      "Testes Unitários",
      "Testes End-to-End",
      "Testes de Integração",
    ],
  },
  {
    category: "Integração e Middleware",
    icon: <Puzzle />,
    items: [
      "Integração de APIs",
      "Desenvolvimento de Middleware",
      "Integração SAP",
      "Integração com Monday.com",
      "Integração com Notion",
      "Integração com ZenDesk",
      "Integração com Sistemas Legados",
    ],
  },
  {
    category: "Web Scraping e Automatização",
    icon: <Monitor />,
    items: [
      "Web Scraping",
      "Extração de Dados",
      "Playwright",
      "Beautiful Soup",
    ],
  },
  {
    category: "Outros",
    icon: <Briefcase />,
    items: [
      "Gerenciamento de Projetos",
      "Resolução de Problemas",
      "Redação Técnica",
      "Mentoria e Treinamento",
    ],
  },
];

export default skills;
