import {
  Code,
  Server,
  Database,
  Cloud,
  Cpu,
  PenTool,
  Puzzle,
  Monitor,
  Briefcase,
} from "lucide-react";

export const skills = [
  {
    category: "Frontend",
    icon: <Code />,
    items: [
      "React",
      "Next.js",
      "JavaScript",
      "TypeScript",
      "HTML5",
      "CSS3",
      "Tailwind CSS",
      "Shadcn UI",
      "Responsive Design",
      "UI/UX Design",
    ],
  },
  {
    category: "Backend",
    icon: <Server />,
    items: [
      "Bun",
      "Node.js",
      "NestJS",
      "Express.js",
      "Python",
      "Django",
      "RESTful APIs",
      "GraphQL",
      "Microservices",
      "Serverless Architecture",
      "AWS Lambda",
    ],
  },
  {
    category: "Database",
    icon: <Database />,
    items: [
      "SQL",
      "PostgreSQL",
      "MySQL",
      "MongoDB",
      "Firebase",
      "Supabase",
      "Database Design",
      "Data Modeling",
    ],
  },
  {
    category: "DevOps",
    icon: <Cloud />,
    items: [
      "Docker",
      "GitHub Actions",
      "Vercel",
      "AWS",
      "Azure",
      "Google Cloud Platform (GCP)",
    ],
  },
  {
    category: "AI/ML",
    icon: <Cpu />,
    items: [
      "Transformers",
      "GPT",
      "Claude",
      "Ollama",
      "Fine-Tuning",
      "NLP (Natural Language Processing)",
      "TensorFlow",
      "PyTorch",
    ],
  },
  {
    category: "Tools and Methods",
    icon: <PenTool />,
    items: [
      "Git",
      "GitHub",
      "GitLab",
      "Scrum",
      "Kanban",
      "Domain-Driven Development (DDD)",
      "Unit Testing",
      "End-to-End Testing",
      "Integration Testing",
    ],
  },
  {
    category: "Integration and Middleware",
    icon: <Puzzle />,
    items: [
      "API Integration",
      "Middleware Development",
      "SAP Integration",
      "Monday.com Integration",
      "Notion Integration",
      "ZenDesk Integration",
      "Legacy Systems Integration",
    ],
  },
  {
    category: "Web Scraping and Automation",
    icon: <Monitor />,
    items: ["Web Scraping", "Data Extraction", "Playwright", "Beautiful Soup"],
  },
  {
    category: "Others",
    icon: <Briefcase />,
    items: [
      "Project Management",
      "Problem Solving",
      "Technical Writing",
      "Mentoring and Training",
    ],
  },
];

export default skills;
